### ISSUE TITLE
슈퍼마리오 실행환경 설치

### ISSUE THREAD

**Issue by WinteringAsch** [SKKUCS/graduationProject#8]
윈도우로는 실행환경 설치가 여의치 않고, 맥북이 없어서 리눅스 환경을 구축하려고 하고 있음.
현재 시도해본 것으로는
1. Windows Subsystem for Linux(WSL)을 이용
tensorflow 설치, gym, gym-pull까지 설치했으나, 그 과정에서 일부 패키지가 정상적으로 설치되지 않아 실패, 설치되지 않는 패키지를 찾아보니 라이선스가 유료라 다른 방법을 찾아봄. 분명 슈퍼마리오 실행하는 다른 튜토리얼에서는 이거때문에 문제가 생겼다는 말은 못봐서 저 패키지때문에 실행이 안될꺼같진 않음.
결국 설치를 끝내고 실행을 시도해 보았으나, 과정에서는 log 디렉토리를 찾을 수 없다는 오류가 발생했고, 이를 새로 생성해줘도 해결하지 못했다.
2. cygwin을 통해서
이건, cygwin에 대한 이해도가 거의 없는 상태에서 시도했던 것이라 그다지 소득이 없었음. 좀더 공부를 하면서 다시 해봐야 할듯 하다.
3. Ubuntu를 통해서
현재 시도중인 방법. 버전은 18.04 LTS. 진척이 있으면 추가하겠음...

**Comment by WinteringAsch** [comment]
음, 여전히 아직 실행은 못했고, 꾸준히 발견되는 오류를 이야기하자면,
1. libav-tools 설치오류. 찾아보니 ffmpeg에서 갈라져 나온거라 하는데, 그래서 ffmpeg를 대신 설치해봤음. avconv를 쓰느냐 ffmpeg를 쓰느냐 차이라는데... 만약 이거때문에 오류가 발생한다면 저 키워드가 뜰듯.
2. mujoco-py 설치오류. 위에도 얘기했지만 아마 이건 유료 라이선스 인듯 하다... 직접적으로 사용되는 패키지는 아닐듯 해서(알고리즘들이 포함된 Baselines 설치과정에서 뜨는거로 봐선) 일단 넘김.
3. Gym_pull  import 오류.  Gym pull이 Gym에 슈퍼마리오 환경을 덧씌워주는 패키진데, gym의 버전이 바뀌면서 오류가 발생한다고 한다. Gym의 버젼을 0.9.4로 지정해서 설치하면 해결되지 않을까... 했는데, 
https://github.com/Kautenja/gym-super-mario-bros
일단 이걸 찾게되서 이쪽으로 설치, 실행을 시도해 보려고 함.

**Comment by JesungKoo** [comment]
아주 생 지옥이야 여기
슈퍼마리오를 향하여..
python 설치
pip3 install --user --upgrade tensorflow
python3 -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose

brew install fceux
pip3 install gym
pip3 install opencv-python
brew install openmpi
pip3 install git+https://github.com/openai/baselines

pip3 install git+https://github.com/chris-chris/gym-super-mario
git clone https://github.com/chris-chris/mario-rl-tutorial
pip3 install python-gflags 

python3 train.py

gflags 이후 오류


1.
conv가 없음 --> acktr/utils.py 에서 a2c로 옮겨간 것을 확인(?) https://github.com/chris-chris/pysc2-examples/issues/12
그래서 acktr policies.py 의 코드를 조금 수정해보았다.

그러나 바로 a2c.utils를 가리키게 하니 dense 와 kl_div에서 문제가 발생함(해당 함수는 그대로 acktr에 있었음)
따라서 이것들을 분리한 구조로 바꿈.

2.
다른 파일에서 오류가 생기기 시작했다. policies는 정리된 것 같으니 acktr_disc.py를 확인해봄. 마찬가지로 a2c문제였는데, mse가 정의되어 있음에도 임포트가 안되는 문제 발생.
--> mse 정의를 아예 물리적으로 옮겨와서 해결

3.
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ppaquette_gym_super_mario/__init__.py", line 2, in <module>
    from gym.scoreboard.registration import add_task, add_group
ModuleNotFoundError: No module named 'gym.scoreboard'

일단 라이브러리를 열어서 주석처리해버림ㅋㅋㅋㅋ 그래서 어떻게 되었을까요...?

4.
add_group() got an unexpected keyword argument 'id'
env : ppaquette/SuperMarioBros-1-1-v0
algorithm : deepq
timesteps : 2000000
exploration_fraction : 0.5
prioritized : False
dueling : False
num_cpu : 4
lr : 0.0005
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.uint8'>. Please provide explicit dtype.
WARN: Environment '<class 'ppaquette_gym_super_mario.super_mario_bros.SuperMarioBrosEnv'>' has deprecated methods '_step' and '_reset' rather than 'step' and 'reset'. Compatibility code invoked. Set _gym_disable_underscore_compat = True to disable this behavior.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.uint8'>. Please provide explicit dtype.
2018-11-02 19:00:45.581586: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 243, in main
    train_dqn(env_id=FLAGS.env, num_timesteps=FLAGS.timesteps)
  File "train.py", line 127, in train_dqn
    callback=deepq_callback
  File "/Users/silvermist/workspace/ai/mario-rl-tutorial/deepq/deepq.py", line 181, in learn
    param_noise=param_noise
  File "/Users/silvermist/workspace/ai/mario-rl-tutorial/deepq/build_graph.py", line 341, in build_train
    act_f = build_act(make_obs_ph, q_func, num_actions, scope=scope, reuse=reuse)
  File "/Users/silvermist/workspace/ai/mario-rl-tutorial/deepq/build_graph.py", line 146, in build_act
    observations_ph = U.ensure_tf_input(make_obs_ph("observation"))
AttributeError: module 'baselines.common.tf_util' has no attribute 'ensure_tf_input'

여기서 대책이 안보여서 지지치고 말았던 것임

**Comment by JesungKoo** [comment]
https://becominghuman.ai/getting-mario-back-into-the-gym-setting-up-super-mario-bros-in-openais-gym-8e39a96c1e41

아예 이걸로 바꾸어 해보았는데, fceux로 마리오를 실행하는 부분에서 문제가 있음을 확인함. 실행이 안돼... 그냥 롬이 안돼 이유를 모르겠어

**Comment by WinteringAsch** [comment]
벌써 원래 실행해보기로 했던 11일... 좀더 해보긴 했는데, 아직 진척이 없네.
오류발생 -> 검색 -> 시도 -> 다른 오류 발생의 반복...
난 이게 윈도우/우분투 문제인줄 알았는데, 너도 뜨는거 보면 딱히 내쪽만의 문제는 아닌가봐.
내일 만나서 할수 있는만큼 더 해보자...

+ 맞다, 어느쪽이든 한쪽이 실행하고 나면 그걸 기준으로 깃헙에 코드 올려가면서 하는게 어떨까 싶어. 만약 그게 OSX이면 내쪽에서 어떻게든 방법을 찾아야겠지...
+ 교수님께 주제 관련해서 조언을 좀 들어야 할꺼 같아.

**Comment by JesungKoo** [comment]
코드 올려야 되는거랑 조언 듣는거 모두 공감. 하.. 학습은 커녕 환경을 실행하고 에이전트 움직이는걸 못하니까 정말 답답하다

**Comment by WinteringAsch** [comment]
![image](https://user-images.githubusercontent.com/23088321/48335523-5aa9ca00-e6a1-11e8-9eec-851fc6c850d1.png)
...뭐야 왜 돼
일단 랜덤으로 움직이는거 실행만 확인하고 종료함.

**Comment by WinteringAsch** [comment]
https://medium.com/@wonseokjung_95449/%EA%B0%95%ED%99%94%ED%95%99%EC%8A%B5%EC%9C%BC%EB%A1%9C-%EB%98%91%EB%98%91%ED%95%9C-%EC%8A%88%ED%8D%BC%EB%A7%88%EB%A6%AC%EC%98%A4-%EB%A7%8C%EB%93%A4%EA%B8%B0-87c423f46b05

**Comment by NeighborhoodCoding** [comment]
cygwin을 통해서 하고 있는데요 homebrew는 어떻게 설치할 수 있나요?? VM으로 linux사용은 너무 힘들어서 되도록 windows환경에서 마리오 훈련시키고 싶습니다 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
Cygwin에서 fceux도 일단 포팅이 안된거 같습니다.
